### PR TITLE
#162685672 Authors should be able to tag articles

### PR DESCRIPTION
**Pull request by BarnaTB**
**What does this PR do?**
This PR enables users to add to tags to their articles when they author them.

**Description of Task to be completed?**
The application should enable a user to be able to add a tag to an article.

**Link to pivotal tracker story**
[#162685672](https://www.pivotaltracker.com/story/show/162685672)

**How should this be manually tested?**
Before testing run these commands in cmd

`git clone https://github.com/andela/Ah-backend-guardians.git`

`cd Ah-backend-guardians`

`git checkout ft-tag-articles-162685672`

`virtualenv env`

`. env/bin/activate`

`pip install -r requirements.txt`

Create a postgres database and a `.env` file in your root directory and add the following configurations.
```
SECRET_KEY=andela_sjdndkjghdf78872

DB_NAME=your_database_name

DB_USER=database_user

DB_PASSWORD=database_password

DB_HOST=127.0.0.1

ALLOWED_HOSTS=.localhost, .herokuapp.com

EMAIL_PORT=587

EMAIL_HOST_USER = gauthorshaven@gmail.com

EMAIL_HOST_PASSWORD = guardiansauthors
```
Open Postman and type `http://localhost:8000/api/articles/` in URL text box and enter the data according to the body of this screenshot, running a **POST** request and the output you get back should be as in the response part of the screenshot.

image

### CODE REVIEW

**Review by fahadmak — COMMENTED** [review]
This description is different from the title of the PR
`What does this PR do?
This PR enables users to follow each other's profiles and optionally unfollow each other.`

**Comment by fahadmak** [comment]
why don't use a descriptive url to show what particular article your tagging `http://localhost:8000/api/articles/<slug>/tag/` and do you need to like post the title and body again when your tagging.

**Comment by BarnaTB** [comment]
> This description is different from the title of the PR
> `What does this PR do? This PR enables users to follow each other's profiles and optionally unfollow each other.`

@fahadmak this issue has been fixed so please review again. Thanks.

**Review by fahadmak — APPROVED** [review]
LGTM

**Review by myrdstom — APPROVED** [review]
LGTM

**Review by archbishop12 — APPROVED** [review]
LGTM @BarnaTB I am merging this.

**Pull request merged**
