### PR TITLE
#162685669 User can Favorite an Article

### PR DESCRIPTION
**Pull request by moseskamira**
#### What Does This PR Do?
This PR enables a user to favorite an article
#### Link To Pivotal Tracker Story
#162685669
#### How Should This Be Manually Tested

- Fetching the branch 'ft-favorite-article-162685669' onto your local machine

- Run the App

- Fetch the Article of interest by using the url: http://127.0.0.1:8000/api/articles/slug/

- Using POST method, append the word 'favorite' on to the above url to Favorite the Article: url should appear as below; http://127.0.0.1:8000/api/articles/slug/favorite/

- Using the PUT method on the same url, the Article shall be Unfavorited
#### NOTE
You do not need to pass anything in the body
#### Snapshots
screen shot 2019-01-22 at 9 07 33 pm
screen shot 2019-01-22 at 9 08 44 pm

### CODE REVIEW

**Comment by Opio-Emmanuel-Omona** [comment]
@moseskamira When I unfavorite an article, the favorite count isn't reducing. Please Ensure that it decrements.

**Review by Opio-Emmanuel-Omona — COMMENTED** [review]
@moseskamira 
When I unfavorite an article, the favorite count remains as it was. Please ensure that it decrements.

**Comment by moseskamira** [comment]
> @moseskamira
> When I unfavorite an article, the favorite count remains as it was. Please ensure that it decrements.

Thanks @Opio-Emmanuel-Omona  I have worked on it and now it is fine

**Comment by moseskamira** [comment]
This PR has been closed as a new branch has been created and a new [#PR](https://github.com/andela/Ah-backend-guardians/pull/34) made.

**Pull request closed without merging**
