### PR TITLE
bug(profiles): Users can view username amongst other credentials

### PR DESCRIPTION
**Pull request by myrdstom**
**What does this PR do?**
This PR creates a `profile` app separate from the `users` app to enable users to manage their profiles as per separation of concerns

Link to pivotal tracker story
[#163944660](https://www.pivotaltracker.com/story/show/163944660)

**How should this be manually tested?**
Follow these steps in the command terminal:-

Clone this repository by running in this command below
git clone https://github.com/andela/Ah-backend-guardians.git

Change working directory to Ah-backend-guardians
cd Ah-backend-guardians

Create a virtual environment.
virtualenv --python=pyhton3 venv

Activate the virtual environment
source venv/bin/activate

Add the following enviroment varialbles to your .env

```
EMAIL_HOST_USER= gauthorshaven@gmail.com

EMAIL_HOST_PASSWORD = guardiansauthors

EMAIL_PORT = 587

cloud_name = myrdstom

API_KEY = 771354771337349

API_SECRET = _khav7PfkzwqKMlOwHHsl5IhbvM

TWITTER_CONSUMER_KEY = annEeggI3NfH8xqWDTPU2O0Ve

TWITTER_CONSUMER_SECRET = w5tVQ6AnWluKdYUJo8aJrVurofat0Wl7qIwePvgqG3Sb57YtBg

WORD_LENGTH = 5

WPM = 200

```
Install the dependencies in the requirements.txt file using pip
`pip install -r requirements.txt`

Run this command
`python manage.py test` to run the tests

To run the application, run the command below
`python manage.py runserver`

Copy and paste this link into postman `http://127.0.0.1:8000/api/profiles/`  and  the  data  returned when viewing a profile should look like the sample below:
```
{
    "profile": [
        {
            "email": "nserekopaul@ymail.com",
            "username": "paul",
            "bio": null,
            "image": null,
            "first_name": "",
            "last_name": ""
        }
```

### CODE REVIEW

**Comment by Opio-Emmanuel-Omona** [comment]
@myrdstom the PR description doesn't show us how to test that the profiles actually return the username or what to expect as the result.

**Comment by Opio-Emmanuel-Omona** [comment]
@myrdstom the PR description doesn't show us how to test that the profiles actually return the username or what to expect as the result.

Otherwise it looks good and I've tested it after.

**Review by fahadmak — APPROVED** [review]
LGTM

**Review by tomuhenry — APPROVED** [review]
LGTM

**Pull request merged**
