### PR TITLE
#162685655 Deploy the application to heroku 

### PR DESCRIPTION
**Pull request by moseskamira**
**What does this PR do?**
This PR delivers a chore that Deploys the App to Heroku

**Description of Task to be completed?**
The task involves pthe following;
- creating a procfile that enables heroku to identify the app.
- Editing the requirements.txt file to include the gunicorn
- Adding the import django_heroku in the settings.py
The task to be completed is intended to ensuring that the deployed app works on heroku.

**What are the relevant Pivotal Tracker stories?**
[#162685655](https://www.pivotaltracker.com/story/show/162685655)

**How should it be manually tested?**
Run the Links below in your browser. However, the link to the production app runs only when merged to master.
Links:
staging app: https://ah-backend-guardians-staging.herokuapp.com/

production app: https://ah-backend-guardians.herokuapp.com/

### CODE REVIEW

**Review by BarnaTB — CHANGES_REQUESTED** [review]
The staging application throws an `application error`. I think it'd be great if you worked on that. Probably it's because of how you named your `Procfile`. Note that it should be an uppercase `P`.

**Comment by tomuhenry** [comment]
@moseskamira I think you should do a rebase to resolve conflict, sending a resource to help...

**Review by tomuhenry — COMMENTED** [review]
Rebase to solve the conflict

**Comment by archbishop12** [comment]
@moseskamira Please reduce the number of your commits to a maximum of 3 and also fix the pr title.

**Review by BarnaTB — APPROVED** [review]
LGTM! Great work! You might need to squash your commits though because they're too many.

**Review by VivianDoreen — APPROVED** [review]
LGTM, Great work. The instructions for testing the story were easy to follow and implement how the story works.

**Review by archbishop12 — APPROVED** [review]
LGTM @moseskamira I am merging this

**Pull request merged**
